config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'

  resources :artists do
    resources :songs
  end

  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'



  # # artists routes
  # get     '/artists',          to: 'artists#index'
  # get     '/artists/new',      to: 'artists#new'
  # post    '/artists',          to: 'artists#create'
  #
  # get     '/artists/:id',      to: 'artists#show'
  # get     '/artists/:id/edit', to: 'artists#edit'
  # put     '/artists/:id',      to: 'artists#update'
  # delete  '/artists/:id',      to: 'artists#destroy'
  #
  # # songs routes
  # get     '/songs',          to: 'songs#index'
  # get     '/songs/new',      to: 'songs#new'
  # post    '/songs',          to: 'songs#create'
  #
  # get     '/songs/:id',      to: 'songs#show'
  # get     '/songs/:id/edit', to: 'songs#edit'
  # put     '/songs/:id',      to: 'songs#update'
  # delete  '/songs/:id',      to: 'songs#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  has_many :artists
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate

  private
  def authenticate
    if !session[:user]
      redirect_to "/sign_in"
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # index
  def index
    @artists = User.find(session[:user]["id"]).artists
  end

  # new
  def new
    @artist = Artist.new
  end

  # create
  def create
    @user = User.find(session[:user]["id"])
    @artist = @user.artists.create!(artist_params)

    redirect_to artist_path(@artist)
  end

  #show
  def show
    @artist = Artist.find(params[:id])
  end

  # edit
  def edit
    @artist = Artist.find(params[:id])
  end


  # update
  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)

    redirect_to artist_path(@artist)
  end

  # destroy
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to artists_path
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :photo_url, :nationality)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # index
  def index
    @songs = Song.all
  end

  # new
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  # create
  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create!(song_params)

    redirect_to artist_path(@artist)
  end

  #show
  def show
    @artist = Artist.find(params[:artist_id])
    @song = Song.find(params[:id])
  end

  # edit
  def edit
    @artist = Artist.find(params[:artist_id])
    @song = Song.find_by(artist_id: @artist.id )
  end

  # update
  def update
    @song = Song.find(params[:id])
    @song.update(song_params)
    @artist = Artist.find(params[:artist_id])

    redirect_to artist_song_path(@artist, @song)
  end

  # destroy
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    @artist = Artist.find(params[:artist_id])

    redirect_to artist_path(@artist)
  end

  private
  def song_params
    params.require(:song).permit(:title, :album, :preview_url, :artist_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate

  def sign_up
  end

  def sign_up!
    user = User.new(
      username: params[:username],
      password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    flash[:notice] = message
    redirect_to action: :sign_up
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist!"
      redirect_to action: :sign_up
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      message = "Your password's wrong!"
      redirect_to action: :sign_in
    else
      message = "You're signed in, #{@user.username}! "
      cookies[:username] = {
        value: @user.username,
        expires: 100.years.from_now
      }
      flash[:notice] = message
      session[:user] = @user
      redirect_to artists_path
    end
    flash[:notice] = message

  end

  def sign_out
    reset_session
    flash[:notice] = "You're signed out!"
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(artist) do |f| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="field">
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%= f.submit %>
<% end %>

<%= form_for @artist, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/artists/index.html.erb
<h2>Artists <%= link_to "(+)", new_artist_path %></h2>

<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.name, artist %>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h2>New Artist</h2>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h2><%= @artist.name %> <%= link_to "(edit)", edit_artist_path(@artist) %></h2>
<h4><%= @artist.nationality %></h4>

<%= image_tag @artist.photo_url, class: "artist-photo" %>

<h3>Songs <%= link_to "(+)", new_artist_song_path(@artist) %></h3>

<ul>
  <% @artist.songs.each do |song| %>
    <li>
      <%= link_to "#{song.title} (#{song.album})", artist_song_path(@artist, song) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TunrRails5RoutesAndResources</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Tun.r</h1>
    <nav>
      <% if session[:user] %>
        <a href="/sign_out"><%= session[:user]["username"] %>: sign out</a></h2>
      <% else %>
        <a href="/sign_up">Sign up</a>
        <a href="/sign_in">Sign in</a>
      <% end %>
      <a href="/artists">Artists</a>
    </nav>
    <br>
    <em><%= flash[:notice] %></em>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :album %>
    <%= f.text_field :album %>
  </div>

  <div class="field">
    <%= f.label :preview_url %>
    <%= f.text_field :preview_url %>
  </div>

  <div class="field">
    <%= f.label :artist_id %>
    <%= f.text_field :artist_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h2>Edit Song</h2>

<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :preview_url %>
  <%= f.text_field :preview_url %>

  <%= f.label :artist_id %>
  <%= f.text_field :artist_id %>

  <%= f.submit %>
<% end %>

<%= form_for [@artist, @song], method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/songs/index.html.erb
<h2>Songs <%= link_to "(+)", new_song_path %></h2>

<ul>
  <% @songs.each do |song| %>
    <li>
      <%= link_to "#{song.title} - #{song.artist.name}", song %>
    </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h2>New Song</h2>

<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :preview_url %>
  <%= f.text_field :preview_url %>

  <%= f.label :artist_id %>
  <%= f.text_field :artist_id %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h2><%= @song.title %> <%= link_to "(edit)", edit_artist_song_path(@artist, @song) %></h2>
<h3>By: <%= @song.artist.name %></h3>

Album: <%= @song.album %></br>

<audio controls src="<%= @song.preview_url %>"></audio>

app/views/users/sign_in.html.erb
<h2>Sign in</h2>
<%= form_tag("/sign_in", method: "post") do %>
  <input type="text" name="username" placeholder="username" value="<%= cookies[:username] %>"/>
  <input type="password" name="password" placeholder="password" />
  <input type="submit" value="Sign in" />
<% end %>

app/views/users/sign_up.html.erb
<h2>Sign up</h2>
<%= form_tag("/sign_up", method: "post") do %>
  <input type="text" name="username" placeholder="username" />
  <input type="password" name="password" placeholder="password" />
  <input type="password" name="password_confirmation" placeholder="password again" />
  <input type="submit" value="Sign up" />
<% end %>